### ISSUE TITLE
mycobot 280 jetson nano MyCobotSocket

### ISSUE THREAD

**Issue by alex-f1tor** [elephantrobotics/mycobot_ros#81]
Hi! I try to launch official test [script](https://github.com/elephantrobotics/mycobot_ros/blob/noetic/mycobot_280/mycobot_280jn/scripts/test.py) for mycobot 280 jetson nano, but got the following error during the Socket initialization:

`ms=MyCobotSocket('192.168.125.226',9000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elephant/.local/lib/python3.6/site-packages/pymycobot/mycobotsocket.py", line 61, in __init__
    self.sock = self.connect_socket()
  File "/home/elephant/.local/lib/python3.6/site-packages/pymycobot/mycobotsocket.py", line 70, in connect_socket
    sock.connect((self.SERVER_IP, self.SERVER_PORT))
OSError: [Errno 101] Network is unreachable
`
the IP and baud were hardcoded in the script (I didn't change anything)

**Comment by wangWking** [comment]
Please make sure to run the server script in the mycobot 280 jetson nano machine. After the script runs successfully, run the ROS-related programs from the client.
